### PR TITLE
Pass Form SS to children as a prop

### PR DESCRIPTION
**Pull request by grsabreu**
Hey man! Great work with the package.
So, this is a thing that I needed to get the field errors using the form's schema within the children.
Would be nice to have this on the official version.

### CODE REVIEW

**Comment by grsabreu** [comment]
@coniel ? any hint?

**Comment by coniel** [comment]
Hey, sorry, been super busy these past few days. This is great, thanks a lot! I see you also changed the way the form data is retrieved on submit. I like your solution (it also looks like it will fix an issue I just discovered when passing a doc into the form for update forms). I just want to check that it works on all inputs in both the Semantic UI and Material UI versions before merging (which one are you using btw?).

I need to do some work on displaying error messages. As you've probably noticed, at the moment it just displays whatever Simple Schema returns. So for any error besides "required" it's pretty useless. If you're able to help with that I would appreciate it a lot!

**Comment by grsabreu** [comment]
Thanks for giving feedback!
I'm using my own UI components, so neither Semantic or Material. For error messages, this is how I'm doing with my components:

 ```
import React from 'react';

const Field = React.createClass({
  getSSError(){
    return this.props.error && this.props.formSchema
              .messageForError(this.props.errorText, this.props.name);
  },

  render(){
    return (
      <label>
        {this.props.label}
        <input
          type={this.props.type || 'text'}
          name={this.props.name}
          placeholder={this.props.placeholder}
        />
        <span className="error">{this.getSSError()}</span>
      </label>
    );
  }
});

export default Field;
```

**Comment by grsabreu** [comment]
Hey, I'm creating a package from my Field component that depends on this changes. It will be like `afQuickField`.

**Comment by coniel** [comment]
Cool, I haven't been able to merge this yet because it actually break some input components in both Semantic UI and Material UI so I'll have to fix those first (I'll get around to it today or tomorrow). Let me know when the package is usable and I can list it in the docs here.

**Comment by grsabreu** [comment]
Ooh, get it. I don't tested it with Semantic neither Material.

**Comment by coniel** [comment]
Finally got this in, thanks a lot for your work! I could use a collaborator on the package. Would you be interested?

**Comment by grsabreu** [comment]
Awesome, man!
I also started passing down schema with context and field definitions. So the Field components won't need to be a direct child of Form. They can just use `this.context.formSchema` and `this.context.formFieldDefinitions[ this.props.name ]` to reactively access errors and default values and these stuff.

**Comment by grsabreu** [comment]
mmm but I think that I polished more that in another branch of my fork because I needed it quicker

**Pull request merged**
